[project]
name = "adam"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=7.1.0",
    "matplotlib>=3.10.7",
    "polars>=1.33.1",
    "pyarrow>=21.0.0",
    "seaborn>=0.13.2",
]
